services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: solar_db
    # O Docker injeta as variáveis do arquivo .env aqui dentro
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - solar_network

  app:
    build: ./app
    container_name: solar_processor
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    depends_on:
      - timescaledb
    networks:
      - solar_network

  grafana:
    image: grafana/grafana:latest
    container_name: solar_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb
    networks:
      - solar_network

networks:
  solar_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: